/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const contactPersonOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['contactPerson'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a contact person',
				action: 'Create a contact person',
				routing: {
					request: { method: 'POST', url: '=/contact/companies/{{$parameter["companyId"]}}/persons' },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a contact person',
				action: 'Delete a contact person',
				routing: {
					request: { method: 'DELETE', url: '=/contact/companies/{{$parameter["companyId"]}}/persons/{{$parameter["contactPersonId"]}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get one contact person',
				action: 'Get a contact person',
				routing: {
					request: { method: 'GET', url: '=/contact/companies/{{$parameter["companyId"]}}/persons/{{$parameter["contactPersonId"]}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many contact persons',
				action: 'Get many contact persons',
				routing: {
					request: { method: 'GET', url: '=/contact/companies/{{$parameter["companyId"]}}/persons' },
					operations: {
						pagination: {
							type: 'generic',
							properties: {
								continue: '={{ $response.body.has_more === true }}',
								request: { qs: { page: '={{ $pageCount + 1 }}' } },
							},
						},
					},
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'entries' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a contact person',
				action: 'Update a contact person',
				routing: {
					request: { method: 'PUT', url: '=/contact/companies/{{$parameter["companyId"]}}/persons/{{$parameter["contactPersonId"]}}' },
				},
			},
		],
		default: 'create',
	},
];

export const contactPersonFields: INodeProperties[] = [
	{
		displayName: 'Company ID',
		name: 'companyId',
		type: 'string',
		default: '',
		description: 'ID of the company the contact person belongs to',
		required: true,
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['getAll', 'create', 'get', 'update', 'delete'],
			},
		},
	},
	{
		displayName: 'Contact Person ID',
		name: 'contactPersonId',
		type: 'string',
		default: '',
		description: 'ID of the contact person to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['get', 'update', 'delete'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: { send: { paginate: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['getAll'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		routing: { send: { property: 'page_size', type: 'query', value: '={{ $value }}' }, output: { maxResults: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'string',
				default: '',
				description: 'Field to sort by. Only the fields the endpoint documents are accepted, and it only takes effect together with Order Direction.',
				routing: { send: { property: 'order_by', type: 'query' } },
			},
			{
				displayName: 'Order Direction',
				name: 'orderDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
				description: 'Sort direction, only effective together with Order By',
				routing: { send: { property: 'order_direction', type: 'query' } },
			},
		],
	},
	{
		displayName: 'First Name',
		name: 'firstName',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'first_name', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Last Name',
		name: 'lastName',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'last_name', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Comment',
				name: 'comment',
				type: 'string',
				default: '',
				routing: { send: { property: 'comment', type: 'body' } },
			},
			{
				displayName: 'Default',
				name: 'default',
				type: 'string',
				default: '',
				routing: { send: { property: 'default', type: 'body' } },
			},
			{
				displayName: 'Department',
				name: 'department',
				type: 'string',
				default: '',
				routing: { send: { property: 'department', type: 'body' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'name@email.com',
				routing: { send: { property: 'email', type: 'body' } },
			},
			{
				displayName: 'Fax',
				name: 'fax',
				type: 'string',
				default: '',
				routing: { send: { property: 'fax', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'string',
				default: '',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				routing: { send: { property: 'mobile', type: 'body' } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				routing: { send: { property: 'phone', type: 'body' } },
			},
			{
				displayName: 'Position',
				name: 'position',
				type: 'string',
				default: '',
				routing: { send: { property: 'position', type: 'body' } },
			},
			{
				displayName: 'Salutation',
				name: 'salutation',
				type: 'string',
				default: '',
				routing: { send: { property: 'salutation', type: 'body' } },
			},
			{
				displayName: 'Skype',
				name: 'skype',
				type: 'string',
				default: '',
				routing: { send: { property: 'skype', type: 'body' } },
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				routing: { send: { property: 'title', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['contactPerson'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Comment',
				name: 'comment',
				type: 'string',
				default: '',
				routing: { send: { property: 'comment', type: 'body' } },
			},
			{
				displayName: 'Default',
				name: 'default',
				type: 'string',
				default: '',
				routing: { send: { property: 'default', type: 'body' } },
			},
			{
				displayName: 'Department',
				name: 'department',
				type: 'string',
				default: '',
				routing: { send: { property: 'department', type: 'body' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'name@email.com',
				routing: { send: { property: 'email', type: 'body' } },
			},
			{
				displayName: 'Fax',
				name: 'fax',
				type: 'string',
				default: '',
				routing: { send: { property: 'fax', type: 'body' } },
			},
			{
				displayName: 'First Name',
				name: 'firstName',
				type: 'string',
				default: '',
				routing: { send: { property: 'first_name', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'string',
				default: '',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
			{
				displayName: 'Last Name',
				name: 'lastName',
				type: 'string',
				default: '',
				routing: { send: { property: 'last_name', type: 'body' } },
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				routing: { send: { property: 'mobile', type: 'body' } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				routing: { send: { property: 'phone', type: 'body' } },
			},
			{
				displayName: 'Position',
				name: 'position',
				type: 'string',
				default: '',
				routing: { send: { property: 'position', type: 'body' } },
			},
			{
				displayName: 'Salutation',
				name: 'salutation',
				type: 'string',
				default: '',
				routing: { send: { property: 'salutation', type: 'body' } },
			},
			{
				displayName: 'Skype',
				name: 'skype',
				type: 'string',
				default: '',
				routing: { send: { property: 'skype', type: 'body' } },
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				routing: { send: { property: 'title', type: 'body' } },
			},
		],
	},
];
