/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const customAttributeOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['customAttribute'] } },
		options: [
			{
				name: 'Archive',
				value: 'archive',
				description: 'Archive a custom attribute',
				action: '',
				routing: {
					request: { method: 'POST', url: '=/settings/custom_attributes/{{$parameter["customAttributeId"]}}/archive' },
				},
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a custom attribute',
				action: 'Create a custom attribute',
				routing: {
					request: { method: 'POST', url: '/settings/custom_attributes' },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a custom attribute',
				action: 'Delete a custom attribute',
				routing: {
					request: { method: 'DELETE', url: '=/settings/custom_attributes/{{$parameter["customAttributeId"]}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get one custom attribute',
				action: 'Get a custom attribute',
				routing: {
					request: { method: 'GET', url: '=/settings/custom_attributes/{{$parameter["customAttributeId"]}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many custom attributes',
				action: 'Get many custom attributes',
				routing: {
					request: { method: 'GET', url: '/settings/custom_attributes' },
					operations: {
						pagination: {
							type: 'generic',
							properties: {
								continue: '={{ $response.body.has_more === true }}',
								request: { qs: { page: '={{ $pageCount + 1 }}' } },
							},
						},
					},
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'entries' } }] },
				},
			},
			{
				name: 'Unarchive',
				value: 'unarchive',
				description: 'Unarchive a custom attribute',
				action: '',
				routing: {
					request: { method: 'POST', url: '=/settings/custom_attributes/{{$parameter["customAttributeId"]}}/unarchive' },
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a custom attribute',
				action: 'Update a custom attribute',
				routing: {
					request: { method: 'PUT', url: '=/settings/custom_attributes/{{$parameter["customAttributeId"]}}' },
				},
			},
		],
		default: 'archive',
	},
];

export const customAttributeFields: INodeProperties[] = [
	{
		displayName: 'Custom Attribute ID',
		name: 'customAttributeId',
		type: 'string',
		default: '',
		description: 'ID of the custom attribute to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['get', 'update', 'delete', 'archive', 'unarchive'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: { send: { paginate: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['getAll'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		routing: { send: { property: 'page_size', type: 'query', value: '={{ $value }}' }, output: { maxResults: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'string',
				default: '',
				description: 'Field to sort by. Only the fields the endpoint documents are accepted, and it only takes effect together with Order Direction.',
				routing: { send: { property: 'order_by', type: 'query' } },
			},
			{
				displayName: 'Order Direction',
				name: 'orderDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
				description: 'Sort direction, only effective together with Order By',
				routing: { send: { property: 'order_direction', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Attributable Type',
		name: 'attributableType',
		type: 'options',
		options: [
			{ name: 'Contact::Company', value: 'Contact::Company' },
			{ name: 'Project', value: 'Project' },
		],
		default: 'Contact::Company',
		required: true,
		routing: { send: { property: 'attributable_type', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Data Type',
		name: 'dataType',
		type: 'options',
		options: [
			{ name: 'Boolean', value: 'boolean' },
			{ name: 'Date', value: 'date' },
			{ name: 'Decimal', value: 'decimal' },
			{ name: 'Integer', value: 'integer' },
			{ name: 'String', value: 'string' },
			{ name: 'Text', value: 'text' },
		],
		default: 'string',
		required: true,
		routing: { send: { property: 'data_type', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'name', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['customAttribute'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Attributable Type',
				name: 'attributableType',
				type: 'options',
				options: [
					{ name: 'Contact::Company', value: 'Contact::Company' },
					{ name: 'Project', value: 'Project' },
				],
				default: 'Contact::Company',
				routing: { send: { property: 'attributable_type', type: 'body' } },
			},
			{
				displayName: 'Data Type',
				name: 'dataType',
				type: 'options',
				options: [
					{ name: 'Boolean', value: 'boolean' },
					{ name: 'Date', value: 'date' },
					{ name: 'Decimal', value: 'decimal' },
					{ name: 'Integer', value: 'integer' },
					{ name: 'String', value: 'string' },
					{ name: 'Text', value: 'text' },
				],
				default: 'string',
				routing: { send: { property: 'data_type', type: 'body' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				routing: { send: { property: 'name', type: 'body' } },
			},
		],
	},
];
