/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */

import type { INodeProperties } from 'n8n-workflow';

import { bankConnectionFields, bankConnectionOperations } from './BankConnectionDescription';
import { bankTransactionFields, bankTransactionOperations } from './BankTransactionDescription';
import { companyFields, companyOperations } from './CompanyDescription';
import { contactPersonFields, contactPersonOperations } from './ContactPersonDescription';
import { customAttributeFields, customAttributeOperations } from './CustomAttributeDescription';
import { estimateFields, estimateOperations } from './EstimateDescription';
import { infoFields, infoOperations } from './InfoDescription';
import { invoiceFields, invoiceOperations } from './InvoiceDescription';
import { paymentTermFields, paymentTermOperations } from './PaymentTermDescription';
import { projectFields, projectOperations } from './ProjectDescription';
import { propositionFields, propositionOperations } from './PropositionDescription';
import { taskFields, taskOperations } from './TaskDescription';
import { timeEntryFields, timeEntryOperations } from './TimeEntryDescription';
import { userFields, userOperations } from './UserDescription';
import { voucherFields, voucherOperations } from './VoucherDescription';
import { voucherDocumentFields, voucherDocumentOperations } from './VoucherDocumentDescription';

export const resourceOptions: INodeProperties = {
	displayName: 'Resource',
	name: 'resource',
	type: 'options',
	noDataExpression: true,
	options: [
		{ name: 'Bank Connection', value: 'bankConnection', description: 'Bank connections, read only' },
		{ name: 'Bank Transaction', value: 'bankTransaction', description: 'Bank transactions, read only' },
		{ name: 'Company', value: 'company', description: 'Customers and suppliers' },
		{ name: 'Contact Person', value: 'contactPerson', description: 'Contact persons of one company' },
		{ name: 'Custom Attribute', value: 'customAttribute', description: 'Custom fields on companies and projects' },
		{ name: 'Estimate', value: 'estimate', description: 'Estimates and quotes' },
		{ name: 'Info', value: 'info', description: 'Static information the other endpoints refer to' },
		{ name: 'Invoice', value: 'invoice', description: 'Outgoing invoices' },
		{ name: 'Payment Term', value: 'paymentTerm', description: 'Payment terms, read only' },
		{ name: 'Project', value: 'project', description: 'Projects' },
		{ name: 'Proposition', value: 'proposition', description: 'Products and services' },
		{ name: 'Task', value: 'task', description: 'Tasks in the time tracker' },
		{ name: 'Time Entry', value: 'timeEntry', description: 'Tracked time' },
		{ name: 'User', value: 'user', description: 'Users, read only' },
		{ name: 'Voucher', value: 'voucher', description: 'Expense vouchers and receipts' },
		{ name: 'Voucher Document', value: 'voucherDocument', description: 'File attachments of one voucher' },
	],
	default: 'invoice',
};

export const resourceProperties: INodeProperties[] = [
	...bankConnectionOperations,
	...bankConnectionFields,
	...bankTransactionOperations,
	...bankTransactionFields,
	...companyOperations,
	...companyFields,
	...contactPersonOperations,
	...contactPersonFields,
	...customAttributeOperations,
	...customAttributeFields,
	...estimateOperations,
	...estimateFields,
	...infoOperations,
	...infoFields,
	...invoiceOperations,
	...invoiceFields,
	...paymentTermOperations,
	...paymentTermFields,
	...projectOperations,
	...projectFields,
	...propositionOperations,
	...propositionFields,
	...taskOperations,
	...taskFields,
	...timeEntryOperations,
	...timeEntryFields,
	...userOperations,
	...userFields,
	...voucherOperations,
	...voucherFields,
	...voucherDocumentOperations,
	...voucherDocumentFields,
];
