/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const infoOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['info'] } },
		options: [
			{
				name: 'Get',
				value: 'get',
				description: 'Get one info',
				action: 'Get an info',
				routing: {
					request: { method: 'GET', url: '/info' },
				},
			},
		],
		default: 'get',
	},
];

export const infoFields: INodeProperties[] = [
];
