/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const projectOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['project'] } },
		options: [
			{
				name: 'Archive',
				value: 'archive',
				description: 'Archive a project',
				action: 'Archive a project',
				routing: {
					request: { method: 'POST', url: '=/projects/{{$parameter["projectId"]}}/archive' },
				},
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a project',
				action: 'Create a project',
				routing: {
					request: { method: 'POST', url: '/projects' },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a project',
				action: 'Delete a project',
				routing: {
					request: { method: 'DELETE', url: '=/projects/{{$parameter["projectId"]}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get one project',
				action: 'Get a project',
				routing: {
					request: { method: 'GET', url: '=/projects/{{$parameter["projectId"]}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many projects',
				action: 'Get many projects',
				routing: {
					request: { method: 'GET', url: '/projects' },
					operations: {
						pagination: {
							type: 'generic',
							properties: {
								continue: '={{ $response.body.has_more === true }}',
								request: { qs: { page: '={{ $pageCount + 1 }}' } },
							},
						},
					},
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'entries' } }] },
				},
			},
			{
				name: 'Unarchive',
				value: 'unarchive',
				description: 'Unarchive a project',
				action: 'Unarchive a project',
				routing: {
					request: { method: 'POST', url: '=/projects/{{$parameter["projectId"]}}/unarchive' },
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a project',
				action: 'Update a project',
				routing: {
					request: { method: 'PUT', url: '=/projects/{{$parameter["projectId"]}}' },
				},
			},
		],
		default: 'archive',
	},
];

export const projectFields: INodeProperties[] = [
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		default: '',
		description: 'ID of the project to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['get', 'update', 'delete', 'archive', 'unarchive'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: { send: { paginate: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['getAll'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		routing: { send: { property: 'page_size', type: 'query', value: '={{ $value }}' }, output: { maxResults: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Company ID',
				name: 'companyId',
				type: 'number',
				default: 0,
				description: 'Filter by company ID',
				routing: { send: { property: 'company_id', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'string',
				default: '',
				description: 'Field of the record to sort by, for example "ID" or "updated_at". Takes effect only together with Order Direction, and a field the endpoint does not know answers with HTTP 500 rather than an error message.',
				routing: { send: { property: 'order_by', type: 'query' } },
			},
			{
				displayName: 'Order Direction',
				name: 'orderDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
				description: 'Sort direction, only effective together with Order By',
				routing: { send: { property: 'order_direction', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'name', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Budget Money',
				name: 'budgetMoney',
				type: 'string',
				default: '',
				routing: { send: { property: 'budget_money', type: 'body' } },
			},
			{
				displayName: 'Budget Time',
				name: 'budgetTime',
				type: 'string',
				default: '',
				routing: { send: { property: 'budget_time', type: 'body' } },
			},
			{
				displayName: 'Budget Time Unit',
				name: 'budgetTimeUnit',
				type: 'options',
				options: [
					{ name: 'Day', value: 'day' },
					{ name: 'Hour', value: 'hour' },
				],
				default: 'hour',
				routing: { send: { property: 'budget_time_unit', type: 'body' } },
			},
			{
				displayName: 'Budget Type',
				name: 'budgetType',
				type: 'options',
				options: [
					{ name: 'Money', value: 'money' },
					{ name: 'Working Time', value: 'working_time' },
				],
				default: 'money',
				routing: { send: { property: 'budget_type', type: 'body' } },
			},
			{
				displayName: 'Color',
				name: 'color',
				type: 'options',
				options: [
					{ name: 'Blue', value: 'blue' },
					{ name: 'Green', value: 'green' },
					{ name: 'Lime', value: 'lime' },
					{ name: 'Orange', value: 'orange' },
					{ name: 'Pink', value: 'pink' },
					{ name: 'Purple', value: 'purple' },
				],
				default: 'blue',
				routing: { send: { property: 'color', type: 'body' } },
			},
			{
				displayName: 'Custom Attributes',
				name: 'customAttributes',
				type: 'json',
				default: '{}',
				description: 'JSON object in the shape the API documents for "custom_attributes"',
				routing: { send: { property: 'custom_attributes', type: 'body', value: '={{ JSON.parse($value) }}' } },
			},
			{
				displayName: 'Customer ID',
				name: 'customerId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'customer.id', type: 'body' } },
			},
			{
				displayName: 'Default Proposition ID',
				name: 'defaultPropositionId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'default_proposition.id', type: 'body' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				routing: { send: { property: 'description', type: 'body' } },
			},
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'end_date', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'boolean',
				default: false,
				description: 'Whether flagged',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'start_date', type: 'body' } },
			},
			{
				displayName: 'Team Members',
				name: 'teamMembers',
				type: 'json',
				default: '[]',
				description: 'JSON array in the shape the API documents for "team_members"',
				routing: { send: { property: 'team_members', type: 'body', value: '={{ JSON.parse($value) }}' } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Budget Money',
				name: 'budgetMoney',
				type: 'string',
				default: '',
				routing: { send: { property: 'budget_money', type: 'body' } },
			},
			{
				displayName: 'Budget Time',
				name: 'budgetTime',
				type: 'string',
				default: '',
				routing: { send: { property: 'budget_time', type: 'body' } },
			},
			{
				displayName: 'Budget Time Unit',
				name: 'budgetTimeUnit',
				type: 'options',
				options: [
					{ name: 'Day', value: 'day' },
					{ name: 'Hour', value: 'hour' },
				],
				default: 'hour',
				routing: { send: { property: 'budget_time_unit', type: 'body' } },
			},
			{
				displayName: 'Budget Type',
				name: 'budgetType',
				type: 'options',
				options: [
					{ name: 'Money', value: 'money' },
					{ name: 'Working Time', value: 'working_time' },
				],
				default: 'money',
				routing: { send: { property: 'budget_type', type: 'body' } },
			},
			{
				displayName: 'Color',
				name: 'color',
				type: 'options',
				options: [
					{ name: 'Blue', value: 'blue' },
					{ name: 'Green', value: 'green' },
					{ name: 'Lime', value: 'lime' },
					{ name: 'Orange', value: 'orange' },
					{ name: 'Pink', value: 'pink' },
					{ name: 'Purple', value: 'purple' },
				],
				default: 'blue',
				routing: { send: { property: 'color', type: 'body' } },
			},
			{
				displayName: 'Custom Attributes',
				name: 'customAttributes',
				type: 'json',
				default: '{}',
				description: 'JSON object in the shape the API documents for "custom_attributes"',
				routing: { send: { property: 'custom_attributes', type: 'body', value: '={{ JSON.parse($value) }}' } },
			},
			{
				displayName: 'Customer ID',
				name: 'customerId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'customer.id', type: 'body' } },
			},
			{
				displayName: 'Default Proposition ID',
				name: 'defaultPropositionId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'default_proposition.id', type: 'body' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				routing: { send: { property: 'description', type: 'body' } },
			},
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'end_date', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'boolean',
				default: false,
				description: 'Whether flagged',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				routing: { send: { property: 'name', type: 'body' } },
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'start_date', type: 'body' } },
			},
			{
				displayName: 'Team Members',
				name: 'teamMembers',
				type: 'json',
				default: '[]',
				description: 'JSON array in the shape the API documents for "team_members"',
				routing: { send: { property: 'team_members', type: 'body', value: '={{ JSON.parse($value) }}' } },
			},
		],
	},
];
