/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const propositionOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['proposition'] } },
		options: [
			{
				name: 'Archive',
				value: 'archive',
				description: 'Archive a proposition',
				action: 'Archive a proposition',
				routing: {
					request: { method: 'POST', url: '=/income/propositions/{{$parameter["propositionId"]}}/archive' },
				},
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a proposition',
				action: 'Create a proposition',
				routing: {
					request: { method: 'POST', url: '/income/propositions' },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a proposition',
				action: 'Delete a proposition',
				routing: {
					request: { method: 'DELETE', url: '=/income/propositions/{{$parameter["propositionId"]}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get one proposition',
				action: 'Get a proposition',
				routing: {
					request: { method: 'GET', url: '=/income/propositions/{{$parameter["propositionId"]}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many propositions',
				action: 'Get many propositions',
				routing: {
					request: { method: 'GET', url: '/income/propositions' },
					operations: {
						pagination: {
							type: 'generic',
							properties: {
								continue: '={{ $response.body.has_more === true }}',
								request: { qs: { page: '={{ $pageCount + 1 }}' } },
							},
						},
					},
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'entries' } }] },
				},
			},
			{
				name: 'Unarchive',
				value: 'unarchive',
				description: 'Unarchive a proposition',
				action: 'Unarchive a proposition',
				routing: {
					request: { method: 'POST', url: '=/income/propositions/{{$parameter["propositionId"]}}/unarchive' },
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a proposition',
				action: 'Update a proposition',
				routing: {
					request: { method: 'PUT', url: '=/income/propositions/{{$parameter["propositionId"]}}' },
				},
			},
		],
		default: 'archive',
	},
];

export const propositionFields: INodeProperties[] = [
	{
		displayName: 'Proposition ID',
		name: 'propositionId',
		type: 'string',
		default: '',
		description: 'ID of the proposition to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['get', 'update', 'delete', 'archive', 'unarchive'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: { send: { paginate: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['getAll'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		routing: { send: { property: 'page_size', type: 'query', value: '={{ $value }}' }, output: { maxResults: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'string',
				default: '',
				description: 'Field of the record to sort by, for example "ID" or "updated_at". Takes effect only together with Order Direction, and a field the endpoint does not know answers with HTTP 500 rather than an error message.',
				routing: { send: { property: 'order_by', type: 'query' } },
			},
			{
				displayName: 'Order Direction',
				name: 'orderDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
				description: 'Sort direction, only effective together with Order By',
				routing: { send: { property: 'order_direction', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Article No',
		name: 'articleNo',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'article_no', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'name', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Proposition Type',
		name: 'propositionType',
		type: 'options',
		options: [
			{ name: 'Ecommerce', value: 'ecommerce' },
			{ name: 'Product', value: 'product' },
			{ name: 'Service', value: 'service' },
		],
		default: 'service',
		required: true,
		routing: { send: { property: 'proposition_type', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Time Unit',
		name: 'timeUnit',
		type: 'options',
		options: [
			{ name: 'Day', value: 'day' },
			{ name: 'Hour', value: 'hour' },
		],
		default: 'hour',
		required: true,
		routing: { send: { property: 'time_unit', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'VAT Rate',
		name: 'vatRate',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'vat_rate', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				routing: { send: { property: 'description', type: 'body' } },
			},
			{
				displayName: 'Price',
				name: 'price',
				type: 'string',
				default: '',
				routing: { send: { property: 'price', type: 'body' } },
			},
			{
				displayName: 'Unit Name 1',
				name: 'unitName1',
				type: 'string',
				default: '',
				routing: { send: { property: 'unit_name_1', type: 'body' } },
			},
			{
				displayName: 'Unit Name N',
				name: 'unitNameN',
				type: 'string',
				default: '',
				routing: { send: { property: 'unit_name_n', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['proposition'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Article No',
				name: 'articleNo',
				type: 'string',
				default: '',
				routing: { send: { property: 'article_no', type: 'body' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				routing: { send: { property: 'description', type: 'body' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				routing: { send: { property: 'name', type: 'body' } },
			},
			{
				displayName: 'Price',
				name: 'price',
				type: 'string',
				default: '',
				routing: { send: { property: 'price', type: 'body' } },
			},
			{
				displayName: 'Proposition Type',
				name: 'propositionType',
				type: 'options',
				options: [
					{ name: 'Ecommerce', value: 'ecommerce' },
					{ name: 'Product', value: 'product' },
					{ name: 'Service', value: 'service' },
				],
				default: 'service',
				routing: { send: { property: 'proposition_type', type: 'body' } },
			},
			{
				displayName: 'Time Unit',
				name: 'timeUnit',
				type: 'options',
				options: [
					{ name: 'Day', value: 'day' },
					{ name: 'Hour', value: 'hour' },
				],
				default: 'hour',
				routing: { send: { property: 'time_unit', type: 'body' } },
			},
			{
				displayName: 'Unit Name 1',
				name: 'unitName1',
				type: 'string',
				default: '',
				routing: { send: { property: 'unit_name_1', type: 'body' } },
			},
			{
				displayName: 'Unit Name N',
				name: 'unitNameN',
				type: 'string',
				default: '',
				routing: { send: { property: 'unit_name_n', type: 'body' } },
			},
			{
				displayName: 'VAT Rate',
				name: 'vatRate',
				type: 'string',
				default: '',
				routing: { send: { property: 'vat_rate', type: 'body' } },
			},
		],
	},
];
