/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const taskOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['task'] } },
		options: [
			{
				name: 'Archive',
				value: 'archive',
				description: 'Archive a task',
				action: '',
				routing: {
					request: { method: 'POST', url: '=/tracker/tasks/{{$parameter["taskId"]}}/archive' },
				},
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a task',
				action: 'Create a task',
				routing: {
					request: { method: 'POST', url: '/tracker/tasks' },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a task',
				action: 'Delete a task',
				routing: {
					request: { method: 'DELETE', url: '=/tracker/tasks/{{$parameter["taskId"]}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get one task',
				action: 'Get a task',
				routing: {
					request: { method: 'GET', url: '=/tracker/tasks/{{$parameter["taskId"]}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many tasks',
				action: 'Get many tasks',
				routing: {
					request: { method: 'GET', url: '/tracker/tasks' },
					operations: {
						pagination: {
							type: 'generic',
							properties: {
								continue: '={{ $response.body.has_more === true }}',
								request: { qs: { page: '={{ $pageCount + 1 }}' } },
							},
						},
					},
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'entries' } }] },
				},
			},
			{
				name: 'Unarchive',
				value: 'unarchive',
				description: 'Unarchive a task',
				action: '',
				routing: {
					request: { method: 'POST', url: '=/tracker/tasks/{{$parameter["taskId"]}}/unarchive' },
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a task',
				action: 'Update a task',
				routing: {
					request: { method: 'PUT', url: '=/tracker/tasks/{{$parameter["taskId"]}}' },
				},
			},
		],
		default: 'archive',
	},
];

export const taskFields: INodeProperties[] = [
	{
		displayName: 'Task ID',
		name: 'taskId',
		type: 'string',
		default: '',
		description: 'ID of the task to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['get', 'update', 'delete', 'archive', 'unarchive'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: { send: { paginate: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		routing: { send: { property: 'page_size', type: 'query', value: '={{ $value }}' }, output: { maxResults: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Project ID',
				name: 'projectId',
				type: 'number',
				default: 0,
				description: 'Filter by project ID',
				routing: { send: { property: 'project_id', type: 'query' } },
			},
			{
				displayName: 'Proposition ID',
				name: 'propositionId',
				type: 'number',
				default: 0,
				description: 'Filter by proposition ID',
				routing: { send: { property: 'proposition_id', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'string',
				default: '',
				description: 'Field to sort by. Only the fields the endpoint documents are accepted, and it only takes effect together with Order Direction.',
				routing: { send: { property: 'order_by', type: 'query' } },
			},
			{
				displayName: 'Order Direction',
				name: 'orderDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
				description: 'Sort direction, only effective together with Order By',
				routing: { send: { property: 'order_direction', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'name', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Complete',
				name: 'complete',
				type: 'string',
				default: '',
				routing: { send: { property: 'complete', type: 'body' } },
			},
			{
				displayName: 'Deadline',
				name: 'deadline',
				type: 'string',
				default: '',
				routing: { send: { property: 'deadline', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'string',
				default: '',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
			{
				displayName: 'Project ID',
				name: 'projectId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'project.id', type: 'body' } },
			},
			{
				displayName: 'Proposition ID',
				name: 'propositionId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'proposition.id', type: 'body' } },
			},
			{
				displayName: 'Relative Costs',
				name: 'relativeCosts',
				type: 'string',
				default: '',
				routing: { send: { property: 'relative_costs', type: 'body' } },
			},
			{
				displayName: 'User ID',
				name: 'userId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'user.id', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Complete',
				name: 'complete',
				type: 'string',
				default: '',
				routing: { send: { property: 'complete', type: 'body' } },
			},
			{
				displayName: 'Deadline',
				name: 'deadline',
				type: 'string',
				default: '',
				routing: { send: { property: 'deadline', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'string',
				default: '',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				routing: { send: { property: 'name', type: 'body' } },
			},
			{
				displayName: 'Project ID',
				name: 'projectId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'project.id', type: 'body' } },
			},
			{
				displayName: 'Proposition ID',
				name: 'propositionId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'proposition.id', type: 'body' } },
			},
			{
				displayName: 'Relative Costs',
				name: 'relativeCosts',
				type: 'string',
				default: '',
				routing: { send: { property: 'relative_costs', type: 'body' } },
			},
			{
				displayName: 'User ID',
				name: 'userId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'user.id', type: 'body' } },
			},
		],
	},
];
