/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const timeEntryOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['timeEntry'] } },
		options: [
			{
				name: 'Archive',
				value: 'archive',
				description: 'Archive a time entry',
				action: '',
				routing: {
					request: { method: 'POST', url: '=/tracker/time_entries/{{$parameter["timeEntryId"]}}/archive' },
				},
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a time entry',
				action: 'Create a time entry',
				routing: {
					request: { method: 'POST', url: '/tracker/time_entries' },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a time entry',
				action: 'Delete a time entry',
				routing: {
					request: { method: 'DELETE', url: '=/tracker/time_entries/{{$parameter["timeEntryId"]}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get one time entry',
				action: 'Get a time entry',
				routing: {
					request: { method: 'GET', url: '=/tracker/time_entries/{{$parameter["timeEntryId"]}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many time entries',
				action: 'Get many time entries',
				routing: {
					request: { method: 'GET', url: '/tracker/time_entries' },
					operations: {
						pagination: {
							type: 'generic',
							properties: {
								continue: '={{ $response.body.has_more === true }}',
								request: { qs: { page: '={{ $pageCount + 1 }}' } },
							},
						},
					},
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'entries' } }] },
				},
			},
			{
				name: 'Unarchive',
				value: 'unarchive',
				description: 'Unarchive a time entry',
				action: '',
				routing: {
					request: { method: 'POST', url: '=/tracker/time_entries/{{$parameter["timeEntryId"]}}/unarchive' },
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a time entry',
				action: 'Update a time entry',
				routing: {
					request: { method: 'PUT', url: '=/tracker/time_entries/{{$parameter["timeEntryId"]}}' },
				},
			},
		],
		default: 'archive',
	},
];

export const timeEntryFields: INodeProperties[] = [
	{
		displayName: 'Time Entry ID',
		name: 'timeEntryId',
		type: 'string',
		default: '',
		description: 'ID of the time entry to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['get', 'update', 'delete', 'archive', 'unarchive'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: { send: { paginate: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['getAll'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		routing: { send: { property: 'page_size', type: 'query', value: '={{ $value }}' }, output: { maxResults: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Billing State',
				name: 'billingState',
				type: 'options',
				options: [
					{ name: 'Archived', value: 'archived' },
					{ name: 'Billable', value: 'billable' },
					{ name: 'Billed', value: 'billed' },
					{ name: 'Unbillable', value: 'unbillable' },
					{ name: 'Unbilled', value: 'unbilled' },
				],
				default: 'billed',
				description: 'Filter by billing state',
				routing: { send: { property: 'billing_state', type: 'query' } },
			},
			{
				displayName: 'Invoice ID',
				name: 'invoiceId',
				type: 'number',
				default: 0,
				description: 'Filter by invoice ID',
				routing: { send: { property: 'invoice_id', type: 'query' } },
			},
			{
				displayName: 'Project ID',
				name: 'projectId',
				type: 'number',
				default: 0,
				description: 'Filter by project ID',
				routing: { send: { property: 'project_id', type: 'query' } },
			},
			{
				displayName: 'Start Time Range End',
				name: 'startTimeRangeEnd',
				type: 'string',
				default: '',
				description: 'Filter by start time. End of date range. As defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z.',
				routing: { send: { property: 'start_time_range_end', type: 'query' } },
			},
			{
				displayName: 'Start Time Range Start',
				name: 'startTimeRangeStart',
				type: 'string',
				default: '',
				description: 'Filter by start time. Beginning of date range. As defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z.',
				routing: { send: { property: 'start_time_range_start', type: 'query' } },
			},
			{
				displayName: 'Task ID',
				name: 'taskId',
				type: 'number',
				default: 0,
				description: 'Filter by task ID',
				routing: { send: { property: 'task_id', type: 'query' } },
			},
			{
				displayName: 'User ID',
				name: 'userId',
				type: 'number',
				default: 0,
				description: 'Filter by user ID',
				routing: { send: { property: 'user_id', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'string',
				default: '',
				description: 'Field of the record to sort by, for example "ID" or "updated_at". Takes effect only together with Order Direction, and a field the endpoint does not know answers with HTTP 500 rather than an error message.',
				routing: { send: { property: 'order_by', type: 'query' } },
			},
			{
				displayName: 'Order Direction',
				name: 'orderDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
				description: 'Sort direction, only effective together with Order By',
				routing: { send: { property: 'order_direction', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Ended At Time',
		name: 'endedAtTime',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'ended_at_time', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Entry Date',
		name: 'entryDate',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'entry_date', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Started At Time',
		name: 'startedAtTime',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'started_at_time', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Billable Duration',
				name: 'billableDuration',
				type: 'number',
				default: 0,
				routing: { send: { property: 'billable_duration', type: 'body' } },
			},
			{
				displayName: 'Comments',
				name: 'comments',
				type: 'string',
				default: '',
				routing: { send: { property: 'comments', type: 'body' } },
			},
			{
				displayName: 'Task ID',
				name: 'taskId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'task.id', type: 'body' } },
			},
			{
				displayName: 'Unbillable',
				name: 'unbillable',
				type: 'boolean',
				default: false,
				description: 'Whether unbillable',
				routing: { send: { property: 'unbillable', type: 'body' } },
			},
			{
				displayName: 'User ID',
				name: 'userId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'user.id', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['timeEntry'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Billable Duration',
				name: 'billableDuration',
				type: 'number',
				default: 0,
				routing: { send: { property: 'billable_duration', type: 'body' } },
			},
			{
				displayName: 'Comments',
				name: 'comments',
				type: 'string',
				default: '',
				routing: { send: { property: 'comments', type: 'body' } },
			},
			{
				displayName: 'Ended At Time',
				name: 'endedAtTime',
				type: 'string',
				default: '',
				routing: { send: { property: 'ended_at_time', type: 'body' } },
			},
			{
				displayName: 'Entry Date',
				name: 'entryDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'entry_date', type: 'body' } },
			},
			{
				displayName: 'Started At Time',
				name: 'startedAtTime',
				type: 'string',
				default: '',
				routing: { send: { property: 'started_at_time', type: 'body' } },
			},
			{
				displayName: 'Task ID',
				name: 'taskId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'task.id', type: 'body' } },
			},
			{
				displayName: 'Unbillable',
				name: 'unbillable',
				type: 'boolean',
				default: false,
				description: 'Whether unbillable',
				routing: { send: { property: 'unbillable', type: 'body' } },
			},
			{
				displayName: 'User ID',
				name: 'userId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'user.id', type: 'body' } },
			},
		],
	},
];
