/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

export const voucherOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['voucher'] } },
		options: [
			{
				name: 'Archive',
				value: 'archive',
				description: 'Archive a voucher',
				action: 'Archive a voucher',
				routing: {
					request: { method: 'POST', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/archive' },
				},
			},
			{
				name: 'Cancel',
				value: 'cancel',
				description: 'Cancel a voucher',
				action: 'Cancel a voucher',
				routing: {
					request: { method: 'POST', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/cancel' },
				},
			},
			{
				name: 'Cancel With Reverse Entry',
				value: 'cancelWithReverseEntry',
				description: 'Cancel a voucher with reverse entry ("Generalumkehr")',
				action: 'Cancel a voucher with reverse entry',
				routing: {
					request: { method: 'POST', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/cancel_with_reverse_entry' },
				},
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a voucher',
				action: 'Create a voucher',
				routing: {
					request: { method: 'POST', url: '/expense/vouchers' },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a voucher',
				action: 'Delete a voucher',
				routing: {
					request: { method: 'DELETE', url: '=/expense/vouchers/{{$parameter["voucherId"]}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get one voucher',
				action: 'Get a voucher',
				routing: {
					request: { method: 'GET', url: '=/expense/vouchers/{{$parameter["voucherId"]}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many vouchers',
				action: 'Get many vouchers',
				routing: {
					request: { method: 'GET', url: '/expense/vouchers' },
					operations: {
						pagination: {
							type: 'generic',
							properties: {
								continue: '={{ $response.body.has_more === true }}',
								request: { qs: { page: '={{ $pageCount + 1 }}' } },
							},
						},
					},
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'entries' } }] },
				},
			},
			{
				name: 'Pay',
				value: 'pay',
				description: 'Mark a voucher as paid',
				action: 'Mark a voucher as paid',
				routing: {
					request: { method: 'POST', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/pay' },
				},
			},
			{
				name: 'PDF',
				value: 'pdf',
				description: 'Download a voucher as a PDF',
				action: 'Download a voucher as a PDF',
				routing: {
					request: { method: 'GET', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/pdf', encoding: 'arraybuffer', json: false },
					output: {
						postReceive: [{ type: 'binaryData', properties: { destinationProperty: 'data' } }],
					},
				},
			},
			{
				name: 'Unarchive',
				value: 'unarchive',
				description: 'Unarchive a voucher',
				action: 'Unarchive a voucher',
				routing: {
					request: { method: 'POST', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/unarchive' },
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a voucher',
				action: 'Update a voucher',
				routing: {
					request: { method: 'PUT', url: '=/expense/vouchers/{{$parameter["voucherId"]}}' },
				},
			},
		],
		default: 'archive',
	},
];

export const voucherFields: INodeProperties[] = [
	{
		displayName: 'Voucher ID',
		name: 'voucherId',
		type: 'string',
		default: '',
		description: 'ID of the voucher to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['get', 'update', 'delete', 'archive', 'unarchive', 'cancel', 'cancelWithReverseEntry', 'pay', 'pdf'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: { send: { paginate: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['getAll'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		routing: { send: { property: 'page_size', type: 'query', value: '={{ $value }}' }, output: { maxResults: '={{ $value }}' } },
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Creditor ID',
				name: 'creditorId',
				type: 'number',
				default: 0,
				description: 'Filter by creditor (company) ID',
				routing: { send: { property: 'creditor_id', type: 'query' } },
			},
			{
				displayName: 'Document Date Range End',
				name: 'documentDateRangeEnd',
				type: 'string',
				default: '',
				description: 'Filter by document date. End of date range.',
				routing: { send: { property: 'document_date_range_end', type: 'query' } },
			},
			{
				displayName: 'Document Date Range Start',
				name: 'documentDateRangeStart',
				type: 'string',
				default: '',
				description: 'Filter by document date. Beginning of date range.',
				routing: { send: { property: 'document_date_range_start', type: 'query' } },
			},
			{
				displayName: 'Project ID',
				name: 'projectId',
				type: 'number',
				default: 0,
				description: 'Filter by project ID',
				routing: { send: { property: 'project_id', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'string',
				default: '',
				description: 'Field of the record to sort by, for example "ID" or "updated_at". Takes effect only together with Order Direction, and a field the endpoint does not know answers with HTTP 500 rather than an error message.',
				routing: { send: { property: 'order_by', type: 'query' } },
			},
			{
				displayName: 'Order Direction',
				name: 'orderDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
				description: 'Sort direction, only effective together with Order By',
				routing: { send: { property: 'order_direction', type: 'query' } },
			},
		],
	},
	{
		displayName: 'Line Items',
		name: 'lineItems',
		type: 'json',
		default: '[]',
		description: 'Positions as a JSON array. "vat_rate" is not a percentage but the name of a tax rate as configured in the account, spelled exactly as Papierkram spells it: "19%", or "0% Ohne USt (Kleinunternehmer)" for a small business, or "Keine Vorsteuer" for a voucher without input tax. Nothing lists the valid names, so copy one from an existing record.',
		required: true,
		routing: { send: { property: 'line_items', type: 'body', value: '={{ JSON.parse($value) }}' } },
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		routing: { send: { property: 'name', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Provenance',
		name: 'provenance',
		type: 'options',
		options: [
			{ name: 'Domestic', value: 'domestic' },
			{ name: 'Eu', value: 'eu' },
			{ name: 'Foreign', value: 'foreign' },
		],
		default: 'domestic',
		required: true,
		routing: { send: { property: 'provenance', type: 'body' } },
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['create'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Creditor ID',
				name: 'creditorId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'creditor.id', type: 'body' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				routing: { send: { property: 'description', type: 'body' } },
			},
			{
				displayName: 'Document Date',
				name: 'documentDate',
				type: 'string',
				default: '',
				description: 'Date of the document as YYYY-MM-DD. The API rejects an invoice without it, answering "Datum muss ausgefüllt werden" (the date is required), although the specification marks the field optional.',
				routing: { send: { property: 'document_date', type: 'body' } },
			},
			{
				displayName: 'Due Date',
				name: 'dueDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'due_date', type: 'body' } },
			},
			{
				displayName: 'Entertainment Persons',
				name: 'entertainmentPersons',
				type: 'json',
				default: '[]',
				description: 'JSON array in the shape the API documents for "entertainment_persons"',
				routing: { send: { property: 'entertainment_persons', type: 'body', value: '={{ JSON.parse($value) }}' } },
			},
			{
				displayName: 'Entertainment Reason',
				name: 'entertainmentReason',
				type: 'string',
				default: '',
				routing: { send: { property: 'entertainment_reason', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'boolean',
				default: false,
				description: 'Whether flagged',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Creditor ID',
				name: 'creditorId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'creditor.id', type: 'body' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				routing: { send: { property: 'description', type: 'body' } },
			},
			{
				displayName: 'Document Date',
				name: 'documentDate',
				type: 'string',
				default: '',
				description: 'Date of the document as YYYY-MM-DD. The API rejects an invoice without it, answering "Datum muss ausgefüllt werden" (the date is required), although the specification marks the field optional.',
				routing: { send: { property: 'document_date', type: 'body' } },
			},
			{
				displayName: 'Due Date',
				name: 'dueDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'due_date', type: 'body' } },
			},
			{
				displayName: 'Entertainment Persons',
				name: 'entertainmentPersons',
				type: 'json',
				default: '[]',
				description: 'JSON array in the shape the API documents for "entertainment_persons"',
				routing: { send: { property: 'entertainment_persons', type: 'body', value: '={{ JSON.parse($value) }}' } },
			},
			{
				displayName: 'Entertainment Reason',
				name: 'entertainmentReason',
				type: 'string',
				default: '',
				routing: { send: { property: 'entertainment_reason', type: 'body' } },
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'boolean',
				default: false,
				description: 'Whether flagged',
				routing: { send: { property: 'flagged', type: 'body' } },
			},
			{
				displayName: 'Line Items',
				name: 'lineItems',
				type: 'json',
				default: '[]',
				description: 'Positions as a JSON array. "vat_rate" is not a percentage but the name of a tax rate as configured in the account, spelled exactly as Papierkram spells it: "19%", or "0% Ohne USt (Kleinunternehmer)" for a small business, or "Keine Vorsteuer" for a voucher without input tax. Nothing lists the valid names, so copy one from an existing record.',
				routing: { send: { property: 'line_items', type: 'body', value: '={{ JSON.parse($value) }}' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				routing: { send: { property: 'name', type: 'body' } },
			},
			{
				displayName: 'Provenance',
				name: 'provenance',
				type: 'options',
				options: [
					{ name: 'Domestic', value: 'domestic' },
					{ name: 'Eu', value: 'eu' },
					{ name: 'Foreign', value: 'foreign' },
				],
				default: 'domestic',
				routing: { send: { property: 'provenance', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Pay Fields',
		name: 'payFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['voucher'],
				operation: ['pay'],
			},
		},
		options: [
			{
				displayName: 'Banking Transaction ID',
				name: 'bankingTransactionId',
				type: 'number',
				default: 0,
				routing: { send: { property: 'banking_transaction.id', type: 'body' } },
			},
			{
				displayName: 'Difference Reason',
				name: 'differenceReason',
				type: 'options',
				options: [
					{ name: 'Mahnung', value: 'mahnung' },
					{ name: 'Schmaelerung', value: 'schmaelerung' },
					{ name: 'Skonto', value: 'skonto' },
					{ name: 'Sonstige', value: 'sonstige' },
					{ name: 'Teilzahlung', value: 'teilzahlung' },
				],
				default: 'sonstige',
				routing: { send: { property: 'difference_reason', type: 'body' } },
			},
			{
				displayName: 'Payment Date',
				name: 'paymentDate',
				type: 'string',
				default: '',
				routing: { send: { property: 'payment_date', type: 'body' } },
			},
			{
				displayName: 'Value',
				name: 'value',
				type: 'number',
				default: 0,
				routing: { send: { property: 'value', type: 'body' } },
			},
		],
	},
];
