/**
 * Generated by tools/generate-descriptions.mjs from openapi/papierkram-v1.json.
 * Do not edit by hand — change the generator or the spec and regenerate.
 */
import type { INodeProperties } from 'n8n-workflow';

import { uploadBinaryFile } from '../GenericFunctions';

export const voucherDocumentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['voucherDocument'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a voucher document',
				action: 'Create a voucher document',
				routing: {
					request: { method: 'POST', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/documents' },
					send: { preSend: [uploadBinaryFile] },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a voucher document',
				action: 'Delete a voucher document',
				routing: {
					request: { method: 'DELETE', url: '=/expense/vouchers/{{$parameter["voucherId"]}}/documents/{{$parameter["voucherDocumentId"]}}' },
				},
			},
		],
		default: 'create',
	},
];

export const voucherDocumentFields: INodeProperties[] = [
	{
		displayName: 'Voucher ID',
		name: 'voucherId',
		type: 'string',
		default: '',
		description: 'ID of the voucher the voucher document belongs to',
		required: true,
		displayOptions: {
			show: {
				resource: ['voucherDocument'],
				operation: ['create', 'delete'],
			},
		},
	},
	{
		displayName: 'Voucher Document ID',
		name: 'voucherDocumentId',
		type: 'string',
		default: '',
		description: 'ID of the voucher document to work on',
		required: true,
		displayOptions: {
			show: {
				resource: ['voucherDocument'],
				operation: ['delete'],
			},
		},
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		description: 'Name of the binary field of the incoming item that holds the file to upload',
		required: true,
		displayOptions: {
			show: {
				resource: ['voucherDocument'],
				operation: ['create'],
			},
		},
	},
];
